services:
  gateway:
    image: nginx
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/htpasswd:/etc/nginx/conf.d/.htpasswd
      - ./etc/cert.pem:/etc/nginx/cert.pem
      - ./etc/cert.key:/etc/nginx/cert.key
    ports:
      - "8443:443"
  alto-frontend:
    image: openalto/alto
    volumes:
      - ./src/alto:/usr/local/lib/python3.10/site-packages/alto
      - ./etc/alto.conf:/opt/alto/etc/alto.conf
    entrypoint: gunicorn
    command: ["-b", "0.0.0.0:8000", "--threads", "4", "--reload", "alto.server.northbound.wsgi", "--preload", "--log-level", "debug", "--capture-output"]
  alto-lg-agent:
    image: openalto/alto
    volumes:
      - ./etc/lg-agent.json:/etc/lg-agent.json
      - ./etc/alto.conf:/opt/alto/etc/alto.conf
    entrypoint: python
    command: ["-m", "alto.agent.manage", "--pid", "/tmp", "start", "-c", "/etc/lg-agent.json", "-D", "cernlg"]
    network_mode: "service:alto-frontend"
  alto-cric-agent:
    image: openalto/alto
    volumes:
      - ./etc/cric-agent.json:/etc/cric-agent.json
      - ./etc/alto.conf:/opt/alto/etc/alto.conf
    entrypoint: python
    command: ["-m", "alto.agent.manage", "--pid", "/tmp", "start", "-c", "/etc/cric-agent.json", "-D", "cric"]
    network_mode: "service:alto-frontend"
  alto-db:
    image: redis
    network_mode: "service:alto-frontend"
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
